module.exports = {
    async up(knex) {
      const regionsExists = await knex.schema.hasTable('regions');
      const communitiesExists = await knex.schema.hasTable('communities');
  
      if (regionsExists) {
        const regions = [
            {"region_id":"51","name":"Ստեփանակերտ","name_eng":"Stepanakert"},
            {"region_id":"52","name":"Ասկերան","name_eng":"Askeran"},
            {"region_id":"53","name":"Հադրութ","name_eng":"Hadrut"},
            {"region_id":"54","name":"Մարտակերտ","name_eng":"Martakert"},
            {"region_id":"55","name":"Մարտունի","name_eng":"Martuni"},
            {"region_id":"56","name":"Շահումյան","name_eng":"Shahumyan"},
            {"region_id":"57","name":"Շուշի","name_eng":"Shushi"},
            {"region_id":"58","name":"Քաշաթաղ","name_eng":"Kashatagh"},
            {"region_id":"99","name":"ԱՆՀԱՅՏ","name_eng":"UNKNOWN"}
        ]
      
          await knex('regions').insert(regions);
      }

      if (communitiesExists) {
        const communities = [
            {"community_id":"999999","name":"ԱՆՀԱՅՏ","name_eng":"UNKNOWN","region_id":"99","type":"99"},
            {"community_id":"5100001","name":"Ստեփանակերտ","name_eng":"Stepanakert","region_id":"51","type":"capital"},
            {"community_id":"5200111","name":"Ասկերան","name_eng":"Askeran","region_id":"52","type":"town"},
            {"community_id":"5200112","name":"Քյաթուկ","name_eng":"Kyatuk","region_id":"52","type":"village"},
            {"community_id":"5200202","name":"Ակնաղբյուր","name_eng":"Aknaghbyur","region_id":"52","type":"village"},
            {"community_id":"5200302","name":"Այգեստան","name_eng":"Aygestan","region_id":"52","type":"village"},
            {"community_id":"5200402","name":"Աստղաշեն","name_eng":"Astghashen","region_id":"52","type":"village"},
            {"community_id":"5200502","name":"Ավետարանոց","name_eng":"Avetaranots","region_id":"52","type":"village"},
            {"community_id":"5200602","name":"Արմենակավան","name_eng":"Armenakavan","region_id":"52","type":"village"},
            {"community_id":"5200702","name":"Պատարա","name_eng":"Patara","region_id":"52","type":"village"},
            {"community_id":"5200802","name":"Բերքաձոր","name_eng":"Berkadzor","region_id":"52","type":"village"},
            {"community_id":"5200902","name":"Դահրավ","name_eng":"Dahrav","region_id":"52","type":"village"},
            {"community_id":"5201002","name":"Դաշուշեն","name_eng":"Dashushen","region_id":"52","type":"village"},
            {"community_id":"5201102","name":"Իվանյան","name_eng":"Ivanyan","region_id":"52","type":"village"},
            {"community_id":"5201202","name":"Լուսաձոր","name_eng":"Lusadzor","region_id":"52","type":"village"},
            {"community_id":"5201302","name":"Խնապատ","name_eng":"Khnapat","region_id":"52","type":"village"},
            {"community_id":"5201402","name":"Խանցք","name_eng":"Khantsk","region_id":"52","type":"village"},
            {"community_id":"5201512","name":"Խաչեն","name_eng":"Khachen","region_id":"52","type":"village"},
            {"community_id":"5201522","name":"Ուրախաչ","name_eng":"Urakhach","region_id":"52","type":"village"},
            {"community_id":"5201602","name":"Խաչմաչ","name_eng":"Khachmach","region_id":"52","type":"village"},
            {"community_id":"5201702","name":"Խնածախ","name_eng":"Khnatsakh","region_id":"52","type":"village"},
            {"community_id":"5201802","name":"Խնձրիստան","name_eng":"Khndzristan","region_id":"52","type":"village"},
            {"community_id":"5201902","name":"Խրամորթ","name_eng":"Khramort","region_id":"52","type":"village"},
            {"community_id":"5202002","name":"Ծաղկաշատ","name_eng":"Tsaghkashat","region_id":"52","type":"village"},
            {"community_id":"5202102","name":"Կարմիր գյուղ","name_eng":"Karmir Gyugh","region_id":"52","type":"village"},
            {"community_id":"5202202","name":"Հարավ","name_eng":"Harav","region_id":"52","type":"village"},
            {"community_id":"5202302","name":"Հիլիս","name_eng":"Hilis","region_id":"52","type":"village"},
            {"community_id":"5202402","name":"Հովսեփավան","name_eng":"Hovsepavan","region_id":"52","type":"village"},
            {"community_id":"5202502","name":"Մադաթաշեն","name_eng":"Madatashen","region_id":"52","type":"village"},
            {"community_id":"5202602","name":"Մխիթարիշեն","name_eng":"Mkhitarishen","region_id":"52","type":"village"},
            {"community_id":"5202702","name":"Մոշխմհատ","name_eng":"Moshkhmhat","region_id":"52","type":"village"},
            {"community_id":"5202802","name":"Նախիջևանիկ","name_eng":"Nakhijevanik","region_id":"52","type":"village"},
            {"community_id":"5202902","name":"Նորագյուղ","name_eng":"Noragyugh","region_id":"52","type":"village"},
            {"community_id":"5203002","name":"Ներքին Սզնեք","name_eng":"Nerkin Sznek","region_id":"52","type":"village"},
            {"community_id":"5203102","name":"Շոշ","name_eng":"Shosh","region_id":"52","type":"village"},
            {"community_id":"5203202","name":"Ջրաղացներ","name_eng":"Jraghatsner","region_id":"52","type":"village"},
            {"community_id":"5203302","name":"Ռև","name_eng":"Rev","region_id":"52","type":"village"},
            {"community_id":"5203412","name":"Սառնաղբյուր","name_eng":"Sarnaghbyur","region_id":"52","type":"village"},
            {"community_id":"5203422","name":"Դահրազ","name_eng":"Dahraz","region_id":"52","type":"village"},
            {"community_id":"5203502","name":"Սարդարաշեն","name_eng":"Sardarashen","region_id":"52","type":"village"},
            {"community_id":"5203602","name":"Սարուշեն","name_eng":"Sarushen","region_id":"52","type":"village"},
            {"community_id":"5203702","name":"Սղնախ","name_eng":"Sghnakh","region_id":"52","type":"village"},
            {"community_id":"5203812","name":"Վարդաձոր","name_eng":"Vardadzor","region_id":"52","type":"village"},
            {"community_id":"5203822","name":"Վարազաբուն","name_eng":"Varazabun","region_id":"52","type":"village"},
            {"community_id":"5203902","name":"Վերին Սզնեք","name_eng":"Verin Sznek","region_id":"52","type":"village"},
            {"community_id":"5204002","name":"Ուղտասար","name_eng":"Ughtasar","region_id":"52","type":"village"},
            {"community_id":"5204112","name":"Փառուխ","name_eng":"Parukh","region_id":"52","type":"village"},
            {"community_id":"5204122","name":"Քարագլուխ","name_eng":"Karaglukh","region_id":"52","type":"village"},
            {"community_id":"5204202","name":"Քռասնի","name_eng":"Krasni","region_id":"52","type":"village"},
            {"community_id":"5300111","name":"Հադրութ","name_eng":"Hadrut","region_id":"53","type":"town"},
            {"community_id":"5300122","name":"Վանք","name_eng":"Vank","region_id":"53","type":"village"},
            {"community_id":"5300132","name":"Տյաք","name_eng":"Tyak","region_id":"53","type":"village"},
            {"community_id":"5300202","name":"Ազոխ","name_eng":"Azokh","region_id":"53","type":"village"},
            {"community_id":"5300302","name":"Ակնաղբյուր","name_eng":"Aknaghbyur","region_id":"53","type":"village"},
            {"community_id":"5300412","name":"Այգեստան","name_eng":"Aygestan","region_id":"53","type":"village"},
            {"community_id":"5300422","name":"Մելիքաշեն","name_eng":"Melikashen","region_id":"53","type":"village"},
            {"community_id":"5300502","name":"Առաջամուղ","name_eng":"Arajamugh","region_id":"53","type":"village"},
            {"community_id":"5300612","name":"Առաքել","name_eng":"Arakel","region_id":"53","type":"village"},
            {"community_id":"5300622","name":"Ձորագյուղ","name_eng":"Dzoragyugh","region_id":"53","type":"village"},
            {"community_id":"5300632","name":"Կարմրաքար","name_eng":"Karmrakar","region_id":"53","type":"village"},
            {"community_id":"5300642","name":"Ջրաբերդ","name_eng":"Jraberd","region_id":"53","type":"village"},
            {"community_id":"5300652","name":"Սարալանջ","name_eng":"Saralanj","region_id":"53","type":"village"},
            {"community_id":"5300662","name":"Քարագլուխ","name_eng":"Karaglukh","region_id":"53","type":"village"},
            {"community_id":"5300702","name":"Արևշատ","name_eng":"Arevshat","region_id":"53","type":"village"},
            {"community_id":"5300812","name":"Բանաձոր","name_eng":"Banadzor","region_id":"53","type":"village"},
            {"community_id":"5300822","name":"Ցոր","name_eng":"Tsor","region_id":"53","type":"village"},
            {"community_id":"5300902","name":"Դրախտիկ","name_eng":"Drakhtik","region_id":"53","type":"village"},
            {"community_id":"5301002","name":"Թաղասեռ","name_eng":"Taghaser","region_id":"53","type":"village"},
            {"community_id":"5301102","name":"Թաղուտ","name_eng":"Taghut","region_id":"53","type":"village"},
            {"community_id":"5301212","name":"Խանձաձոր","name_eng":"Khandzadzor","region_id":"53","type":"village"},
            {"community_id":"5301222","name":"Հայկավան","name_eng":"Haykavan","region_id":"53","type":"village"},
            {"community_id":"5301312","name":"Խծաբերդ","name_eng":"Khtsaberd","region_id":"53","type":"village"},
            {"community_id":"5301322","name":"Արփագետիկ","name_eng":"Arpagetik","region_id":"53","type":"village"},
            {"community_id":"5301332","name":"Պետրոսաշեն","name_eng":"Petrosashen","region_id":"53","type":"village"},
            {"community_id":"5301342","name":"Սպիտակաշեն","name_eng":"Spitakashen","region_id":"53","type":"village"},
            {"community_id":"5301402","name":"Ծակուռի","name_eng":"Tsakuri","region_id":"53","type":"village"},
            {"community_id":"5301512","name":"Ծամձոր","name_eng":"Tsamdzor","region_id":"53","type":"village"},
            {"community_id":"5301522","name":"Սարինշեն","name_eng":"Sarinshen","region_id":"53","type":"village"},
            {"community_id":"5301602","name":"Կարմրակուճ","name_eng":"Karmrakuch","region_id":"53","type":"village"},
            {"community_id":"5301702","name":"Հարթաշեն","name_eng":"Hartashen","region_id":"53","type":"village"},
            {"community_id":"5301802","name":"Հակակու","name_eng":"Hakaku","region_id":"53","type":"village"},
            {"community_id":"5301902","name":"Հին Թաղեր","name_eng":"Hin Tagher","region_id":"53","type":"village"},
            {"community_id":"5302002","name":"Մարիամաձոր","name_eng":"Mariamadzor","region_id":"53","type":"village"},
            {"community_id":"5302102","name":"Մեծ Թաղեր","name_eng":"Mets Tagher","region_id":"53","type":"village"},
            {"community_id":"5302202","name":"Մոխրենես","name_eng":"Mokhrenes","region_id":"53","type":"village"},
            {"community_id":"5302302","name":"Նորաշեն","name_eng":"Norashen","region_id":"53","type":"village"},
            {"community_id":"5302412","name":"Պլեթանց","name_eng":"Pletants","region_id":"53","type":"village"},
            {"community_id":"5302422","name":"Ծաղկավանք","name_eng":"Tsaghkavank","region_id":"53","type":"village"},
            {"community_id":"5302512","name":"Ջրակուս","name_eng":"Jrakus","region_id":"53","type":"village"},
            {"community_id":"5302522","name":"Հողեր","name_eng":"Hogher","region_id":"53","type":"village"},
            {"community_id":"5302602","name":"Վարդաշատ","name_eng":"Vardashat","region_id":"53","type":"village"},
            {"community_id":"5302702","name":"Տող","name_eng":"Togh","region_id":"53","type":"village"},
            {"community_id":"5302802","name":"Տումի","name_eng":"Tumi","region_id":"53","type":"village"},
            {"community_id":"5302902","name":"Ուխտաձոր","name_eng":"Ukhtadzor","region_id":"53","type":"village"},
            {"community_id":"5303002","name":"Քյուրաթաղ","name_eng":"Kyuratagh","region_id":"53","type":"village"},
            {"community_id":"5400111","name":"Մարտակերտ","name_eng":"Martakert","region_id":"54","type":"town"},
            {"community_id":"5400122","name":"Լևոնարխ","name_eng":"Levonarkh","region_id":"54","type":"village"},
            {"community_id":"5400132","name":"Մարալյան Սարով","name_eng":"Maralyan Sarov","region_id":"54","type":"village"},
            {"community_id":"5400202","name":"Աղաբեկալանջ","name_eng":"Aghabekalanj","region_id":"54","type":"village"},
            {"community_id":"5400312","name":"Առաջաձոր","name_eng":"Arajadzor","region_id":"54","type":"village"},
            {"community_id":"5400322","name":"Հայադ","name_eng":"Hayad","region_id":"54","type":"village"},
            {"community_id":"5400402","name":"Գառնաքար","name_eng":"Garnakar","region_id":"54","type":"village"},
            {"community_id":"5400502","name":"Գետավան","name_eng":"Getavan","region_id":"54","type":"village"},
            {"community_id":"5400602","name":"Դրմբոն","name_eng":"Drmbon","region_id":"54","type":"village"},
            {"community_id":"5400702","name":"Զագլիկ","name_eng":"Zaglik","region_id":"54","type":"village"},
            {"community_id":"5400802","name":"Զարդախաչ","name_eng":"Zardakhach","region_id":"54","type":"village"},
            {"community_id":"5400902","name":"Թալիշ","name_eng":"Talish","region_id":"54","type":"village"},
            {"community_id":"5401002","name":"Թբլղու","name_eng":"Tblghu","region_id":"54","type":"village"},
            {"community_id":"5401102","name":"Խնկավան","name_eng":"Khnkavan","region_id":"54","type":"village"},
            {"community_id":"5401202","name":"Ծաղկաշեն","name_eng":"Tsaghkashen","region_id":"54","type":"village"},
            {"community_id":"5401302","name":"Ծմակահող","name_eng":"Tsmakahogh","region_id":"54","type":"village"},
            {"community_id":"5401402","name":"Կիչան","name_eng":"Kichan","region_id":"54","type":"village"},
            {"community_id":"5401502","name":"Կոճողոտ","name_eng":"Kochoghot","region_id":"54","type":"village"},
            {"community_id":"5401602","name":"Կուսապատ","name_eng":"Kusapat","region_id":"54","type":"village"},
            {"community_id":"5401702","name":"Հաթերք","name_eng":"Haterk","region_id":"54","type":"village"},
            {"community_id":"5401802","name":"Հարությունագոմեր","name_eng":"Harutyunagomer","region_id":"54","type":"village"},
            {"community_id":"5401902","name":"Հովտաշեն","name_eng":"Hovtashen","region_id":"54","type":"village"},
            {"community_id":"5402002","name":"Ճանկաթաղ","name_eng":"Chankatagh","region_id":"54","type":"village"},
            {"community_id":"5402102","name":"Մատաղիս","name_eng":"Mataghis","region_id":"54","type":"village"},
            {"community_id":"5402212","name":"Մաղավուզ","name_eng":"Maghavuz","region_id":"54","type":"village"},
            {"community_id":"5402222","name":"Քմքաձոր","name_eng":"Kmkadzor","region_id":"54","type":"village"},
            {"community_id":"5402302","name":"Մեծ շեն","name_eng":"Mets Shen","region_id":"54","type":"village"},
            {"community_id":"5402402","name":"Մեհմանա","name_eng":"Mehmana","region_id":"54","type":"village"},
            {"community_id":"5402502","name":"Մոխրաթաղ","name_eng":"Mokhratagh","region_id":"54","type":"village"},
            {"community_id":"5402602","name":"Ներքին Հոռաթաղ","name_eng":"Nerkin Horatagh","region_id":"54","type":"village"},
            {"community_id":"5402712","name":"Նոր Այգեստան","name_eng":"Nor Aygestan","region_id":"54","type":"village"},
            {"community_id":"5402722","name":"Այգեստան","name_eng":"Aygestan","region_id":"54","type":"village"},
            {"community_id":"5402812","name":"Նոր Կարմիրավան","name_eng":"Nor Karmiravan","region_id":"54","type":"village"},
            {"community_id":"5402822","name":"Կարմիրավան","name_eng":"Karmiravan","region_id":"54","type":"village"},
            {"community_id":"5402912","name":"Նոր Հայկաջուր","name_eng":"Nor Haykajur","region_id":"54","type":"village"},
            {"community_id":"5402922","name":"Հայկաջուր","name_eng":"Haykajur","region_id":"54","type":"village"},
            {"community_id":"5402932","name":"Նոր Ջրաբերդ","name_eng":"Nor Jraberd","region_id":"54","type":"village"},
            {"community_id":"5402942","name":"Ջրաբերդ","name_eng":"Jraberd","region_id":"54","type":"village"},
            {"community_id":"5403012","name":"Նոր Ղազանչի","name_eng":"Nor Ghazanchi","region_id":"54","type":"village"},
            {"community_id":"5403022","name":"Ղազանչի","name_eng":"Ghazanchi","region_id":"54","type":"village"},
            {"community_id":"5403112","name":"Նոր Մարաղա","name_eng":"Nor Maragha","region_id":"54","type":"village"},
            {"community_id":"5403122","name":"Լենինավան","name_eng":"Leninavan","region_id":"54","type":"village"},
            {"community_id":"5403132","name":"Մարաղա","name_eng":"Maragha","region_id":"54","type":"village"},
            {"community_id":"5403212","name":"Նոր Սեյսուլան","name_eng":"Nor Seysulan","region_id":"54","type":"village"},
            {"community_id":"5403222","name":"Հացավան","name_eng":"Hatsavan","region_id":"54","type":"village"},
            {"community_id":"5403232","name":"Սեյսուլան","name_eng":"Seysulan","region_id":"54","type":"village"},
            {"community_id":"5403302","name":"Շահմասուր","name_eng":"Shahmasur","region_id":"54","type":"village"},
            {"community_id":"5403402","name":"Չափար","name_eng":"Chapar","region_id":"54","type":"village"},
            {"community_id":"5403502","name":"Չլդրան","name_eng":"Chldran","region_id":"54","type":"village"},
            {"community_id":"5403612","name":"Պողոսագոմեր","name_eng":"Poghosagomer","region_id":"54","type":"village"},
            {"community_id":"5403622","name":"Ղազարահող","name_eng":"Ghazarahogh","region_id":"54","type":"village"},
            {"community_id":"5403702","name":"Վաղուհաս","name_eng":"Vaghuhas","region_id":"54","type":"village"},
            {"community_id":"5403812","name":"Վանք","name_eng":"Vank","region_id":"54","type":"village"},
            {"community_id":"5403822","name":"Անձավներ","name_eng":"Andzavner","region_id":"54","type":"village"},
            {"community_id":"5403832","name":"Դաշտագլուխ","name_eng":"Dashtaglukh","region_id":"54","type":"village"},
            {"community_id":"5403842","name":"Ծաղկունք","name_eng":"Tsaghkunk","region_id":"54","type":"village"},
            {"community_id":"5403852","name":"Ճրագ","name_eng":"Chrag","region_id":"54","type":"village"},
            {"community_id":"5403862","name":"Նարեշտար","name_eng":"Nareshtar","region_id":"54","type":"village"},
            {"community_id":"5403902","name":"Վարդաձոր","name_eng":"Vardadzor","region_id":"54","type":"village"},
            {"community_id":"5404002","name":"Վարնկաթաղ","name_eng":"Varnkatagh","region_id":"54","type":"village"},
            {"community_id":"5404102","name":"Վերին Հոռաթաղ","name_eng":"Verin Horatagh","region_id":"54","type":"village"},
            {"community_id":"5404212","name":"Տոնաշեն","name_eng":"Tonashen","region_id":"54","type":"village"},
            {"community_id":"5404222","name":"Դաստակերտ","name_eng":"Dastakert","region_id":"54","type":"village"},
            {"community_id":"5404302","name":"Քոլատակ","name_eng":"Kolatak","region_id":"54","type":"village"},
            {"community_id":"5500111","name":"Մարտունի","name_eng":"Martuni","region_id":"55","type":"town"},
            {"community_id":"5500122","name":"Կաքավաձոր","name_eng":"Kakavadzor","region_id":"55","type":"village"},
            {"community_id":"5500132","name":"Քաջավան","name_eng":"Kajavan","region_id":"55","type":"village"},
            {"community_id":"5500202","name":"Աշան","name_eng":"Ashan","region_id":"55","type":"village"},
            {"community_id":"5500302","name":"Ավդուռ","name_eng":"Avdur","region_id":"55","type":"village"},
            {"community_id":"5500402","name":"Բերդաշեն","name_eng":"Berdashen","region_id":"55","type":"village"},
            {"community_id":"5500502","name":"Գիշի","name_eng":"Gishi","region_id":"55","type":"village"},
            {"community_id":"5500602","name":"Եմիշճան","name_eng":"Yemishchan","region_id":"55","type":"village"},
            {"community_id":"5500702","name":"Զարդանաշեն","name_eng":"Zardanashen","region_id":"55","type":"village"},
            {"community_id":"5500802","name":"Թաղավարդ","name_eng":"Taghavard","region_id":"55","type":"village"},
            {"community_id":"5500902","name":"Խերխան","name_eng":"Kherkhan","region_id":"55","type":"village"},
            {"community_id":"5501002","name":"Խնուշինակ","name_eng":"Khnushinak","region_id":"55","type":"village"},
            {"community_id":"5501102","name":"Ծովատեղ","name_eng":"Tsovategh","region_id":"55","type":"village"},
            {"community_id":"5501202","name":"Կաղարծի","name_eng":"Kaghartsi","region_id":"55","type":"village"},
            {"community_id":"5501312","name":"Կարմիր շուկա","name_eng":"Karmir Shuka","region_id":"55","type":"village"},
            {"community_id":"5501322","name":"Սխտորաշեն","name_eng":"Skhtorashen","region_id":"55","type":"village"},
            {"community_id":"5501402","name":"Կոլխոզաշեն","name_eng":"Kolkhozashen","region_id":"55","type":"village"},
            {"community_id":"5501502","name":"Հաղորտի","name_eng":"Haghorti","region_id":"55","type":"village"},
            {"community_id":"5501602","name":"Հացի","name_eng":"Hatsi","region_id":"55","type":"village"},
            {"community_id":"5501702","name":"Հերհեր","name_eng":"Herher","region_id":"55","type":"village"},
            {"community_id":"5501802","name":"Կավահան","name_eng":"Kavahan","region_id":"55","type":"village"},
            {"community_id":"5501902","name":"Ղուզե Ճարտար","name_eng":"Ghuze Chartar","region_id":"55","type":"village"},
            {"community_id":"5502002","name":"Ճարտար","name_eng":"Chartar","region_id":"55","type":"village"},
            {"community_id":"5502102","name":"Մաճկալաշեն","name_eng":"Machkalashen","region_id":"55","type":"village"},
            {"community_id":"5502202","name":"Մյուրիշեն","name_eng":"Myurishen","region_id":"55","type":"village"},
            {"community_id":"5502302","name":"Մսմնա","name_eng":"Msmna","region_id":"55","type":"village"},
            {"community_id":"5502402","name":"Մուշկապատ","name_eng":"Mushkapat","region_id":"55","type":"village"},
            {"community_id":"5502502","name":"Ննգի","name_eng":"Nngi","region_id":"55","type":"village"},
            {"community_id":"5502602","name":"Նոր շեն","name_eng":"Norshen","region_id":"55","type":"village"},
            {"community_id":"5502702","name":"Շեխեր","name_eng":"Shekher","region_id":"55","type":"village"},
            {"community_id":"5502802","name":"Պառավաթումբ","name_eng":"Paravatumb","region_id":"55","type":"village"},
            {"community_id":"5502902","name":"Ջիվանի","name_eng":"Jivani","region_id":"55","type":"village"},
            {"community_id":"5503002","name":"Սարգսաշեն","name_eng":"Sargsashen","region_id":"55","type":"village"},
            {"community_id":"5503102","name":"Սոս","name_eng":"Sos","region_id":"55","type":"village"},
            {"community_id":"5503202","name":"Սպիտակաշեն","name_eng":"Spitakashen","region_id":"55","type":"village"},
            {"community_id":"5503302","name":"Վազգենաշեն","name_eng":"Vazgenashen","region_id":"55","type":"village"},
            {"community_id":"5503402","name":"Վարանդա","name_eng":"Varanda","region_id":"55","type":"village"},
            {"community_id":"5503502","name":"Քարահունջ","name_eng":"Karahunj","region_id":"55","type":"village"},
            {"community_id":"5503602","name":"Քերթ","name_eng":"Kert","region_id":"55","type":"village"},
            {"community_id":"5601801","name":"Քարվաճառ","name_eng":"Karvachar","region_id":"56","type":"town"},
            {"community_id":"5601902","name":"Եղեգնուտ","name_eng":"Yeghegnut","region_id":"56","type":"village"},
            {"community_id":"5602012","name":"Զուար","name_eng":"Zuar","region_id":"56","type":"village"},
            {"community_id":"5602022","name":"Զարկունի","name_eng":"Zarkuni","region_id":"56","type":"village"},
            {"community_id":"5602032","name":"Թութխուն","name_eng":"Tutkhun","region_id":"56","type":"village"},
            {"community_id":"5602042","name":"Հավախաղաց","name_eng":"Havakhaghats","region_id":"56","type":"village"},
            {"community_id":"5602102","name":"Ծար","name_eng":"Tsar","region_id":"56","type":"village"},
            {"community_id":"5602202","name":"Հավսաթաղ","name_eng":"Havsatagh","region_id":"56","type":"village"},
            {"community_id":"5602302","name":"Ճումեն","name_eng":"Chumen","region_id":"56","type":"village"},
            {"community_id":"5602402","name":"Նոր Բրաջուր","name_eng":"Now Brajur","region_id":"56","type":"village"},
            {"community_id":"5602502","name":"Նոր Վերինշեն","name_eng":"Nor Verinshen","region_id":"56","type":"village"},
            {"community_id":"5602602","name":"Չարեկտար","name_eng":"Charektar","region_id":"56","type":"village"},
            {"community_id":"5602702","name":"Ապահեն","name_eng":"Apaven","region_id":"56","type":"village"},
            {"community_id":"5602802","name":"Ասրիկ","name_eng":"Asrik","region_id":"56","type":"village"},
            {"community_id":"5602902","name":"Եղջերունիկ","name_eng":"Yeghjerunik","region_id":"56","type":"village"},
            {"community_id":"5603002","name":"Եղցատեղ","name_eng":"Yeghtsategh","region_id":"56","type":"village"},
            {"community_id":"5603102","name":"Եղցի","name_eng":"Yeghtsi","region_id":"56","type":"village"},
            {"community_id":"5603202","name":"Զառալյուր","name_eng":"Zaralyur","region_id":"56","type":"village"},
            {"community_id":"5603302","name":"Զովք","name_eng":"Zovk","region_id":"56","type":"village"},
            {"community_id":"5603402","name":"Իշխանիկ","name_eng":"Ishkhanik","region_id":"56","type":"village"},
            {"community_id":"5603502","name":"Խոզենեկ","name_eng":"Khozenek","region_id":"56","type":"village"},
            {"community_id":"5603602","name":"Խոփեր","name_eng":"Khoper","region_id":"56","type":"village"},
            {"community_id":"5603702","name":"Ծավալք","name_eng":"Tsavalk","region_id":"56","type":"village"},
            {"community_id":"5603802","name":"Կորեկնեկ","name_eng":"Koreknek","region_id":"56","type":"village"},
            {"community_id":"5603902","name":"Հովվաշեն","name_eng":"Hovvashen","region_id":"56","type":"village"},
            {"community_id":"5604002","name":"Մշենի","name_eng":"Msheni","region_id":"56","type":"village"},
            {"community_id":"5604102","name":"Նոր Բանանց","name_eng":"Nor Banants","region_id":"56","type":"village"},
            {"community_id":"5604202","name":"Նոր Գետաշեն","name_eng":"Nor Getashen","region_id":"56","type":"village"},
            {"community_id":"5604302","name":"Շիկաքար","name_eng":"Shikakar","region_id":"56","type":"village"},
            {"community_id":"5604402","name":"Չափնի","name_eng":"Chapni","region_id":"56","type":"village"},
            {"community_id":"5604502","name":"Ջերմաջուր","name_eng":"Jermajur","region_id":"56","type":"village"},
            {"community_id":"5604602","name":"Ակնաբերդ","name_eng":"Aknaberd","region_id":"56","type":"village"},
            {"community_id":"5604702","name":"Դադիվանք","name_eng":"Dadivank","region_id":"56","type":"village"},
            {"community_id":"5604802","name":"Նոր Էրքեջ","name_eng":"Nor Erkech","region_id":"56","type":"village"},
            {"community_id":"5604902","name":"Նոր Կարաչինար","name_eng":"Nor Karachinar","region_id":"56","type":"village"},
            {"community_id":"5605002","name":"Նոր Մանաշիդ","name_eng":"Nor Manashid","region_id":"56","type":"village"},
            {"community_id":"5605102","name":"Նոր խարխափուտ","name_eng":"Nor Kharkhaput","region_id":"56","type":"village"},
            {"community_id":"5605202","name":"Քնարավան","name_eng":"Knaravan","region_id":"56","type":"village"},
            {"community_id":"5700111","name":"Շուշի","name_eng":"Shushi","region_id":"57","type":"town"},
            {"community_id":"5700122","name":"Ղայբալիշեն","name_eng":"Ghaybalishen","region_id":"57","type":"village"},
            {"community_id":"5700212","name":"Եղցահող","name_eng":"Yeghtsahogh","region_id":"57","type":"village"},
            {"community_id":"5700222","name":"Կանաչ թալա","name_eng":"Kanach Tala","region_id":"57","type":"village"},
            {"community_id":"5700232","name":"Տասը վերստ","name_eng":"Tasy Verst","region_id":"57","type":"village"},
            {"community_id":"5700302","name":"Լիսագոր","name_eng":"Lisagor","region_id":"57","type":"village"},
            {"community_id":"5700412","name":"Հին շեն","name_eng":"Hin Shen","region_id":"57","type":"village"},
            {"community_id":"5700422","name":"Հունանավ","name_eng":"Hunanav","region_id":"57","type":"village"},
            {"community_id":"5700502","name":"Մեծ շեն","name_eng":"Mets Shen","region_id":"57","type":"village"},
            {"community_id":"5700602","name":"Քարին տակ","name_eng":"Karin Tak","region_id":"57","type":"village"},
            {"community_id":"5700702","name":"Քիրսավան","name_eng":"Kirsavan","region_id":"57","type":"village"},
            {"community_id":"5800101","name":"Բերձոր","name_eng":"Berdzor","region_id":"58","type":"town"},
            {"community_id":"5800211","name":"Կովսական","name_eng":"Kovsakan","region_id":"58","type":"village"},
            {"community_id":"5800222","name":"Դիցմայրի","name_eng":"Ditsmayri","region_id":"58","type":"village"},
            {"community_id":"5800232","name":"Քարատակ","name_eng":"Karatak","region_id":"58","type":"village"},
            {"community_id":"5800301","name":"Միջնավան","name_eng":"Mijnavan","region_id":"58","type":"village"},
            {"community_id":"5800411","name":"Որոտան","name_eng":"Vorotan","region_id":"58","type":"village"},
            {"community_id":"5800422","name":"Անդոկաբերդ","name_eng":"Andokaberd","region_id":"58","type":"village"},
            {"community_id":"5800432","name":"Բարկուշատ","name_eng":"Barkushat","region_id":"58","type":"village"},
            {"community_id":"5800442","name":"Դողար","name_eng":"Doghar","region_id":"58","type":"village"},
            {"community_id":"5800452","name":"Վանանդ","name_eng":"Vanand","region_id":"58","type":"village"},
            {"community_id":"5800502","name":"Ալաշկերտ","name_eng":"Alashkert","region_id":"58","type":"village"},
            {"community_id":"5800602","name":"Աղաձոր","name_eng":"Aghadzor","region_id":"58","type":"village"},
            {"community_id":"5800712","name":"Աղանուս","name_eng":"Aghanus","region_id":"58","type":"village"},
            {"community_id":"5800722","name":"Ապարան","name_eng":"Aparan","region_id":"58","type":"village"},
            {"community_id":"5800732","name":"Մեղվաձոր","name_eng":"Meghvadzor","region_id":"58","type":"village"},
            {"community_id":"5800812","name":"Աղավնատուն","name_eng":"Aghavnatun","region_id":"58","type":"village"},
            {"community_id":"5800822","name":"Խաչգետիկ","name_eng":"Khachgetik","region_id":"58","type":"village"},
            {"community_id":"5800832","name":"Հարար","name_eng":"Harar","region_id":"58","type":"village"},
            {"community_id":"5800902","name":"Աղավնո","name_eng":"Aghavno","region_id":"58","type":"village"},
            {"community_id":"5801012","name":"Այգեհովիտ","name_eng":"Aygehovit","region_id":"58","type":"village"},
            {"community_id":"5801022","name":"Լճաշեն","name_eng":"Lchashen","region_id":"58","type":"village"},
            {"community_id":"5801102","name":"Այգեկ","name_eng":"Aygek","region_id":"58","type":"village"},
            {"community_id":"5801212","name":"Արախիշ","name_eng":"Arakhish","region_id":"58","type":"village"},
            {"community_id":"5801222","name":"Աղբրաձոր","name_eng":"Aghbradzor","region_id":"58","type":"village"},
            {"community_id":"5801232","name":"Գահանիստ","name_eng":"Gahanist","region_id":"58","type":"village"},
            {"community_id":"5801242","name":"Հայթաղ","name_eng":"Haytagh","region_id":"58","type":"village"},
            {"community_id":"5801252","name":"Մովսեսաշեն","name_eng":"Movsesashen","region_id":"58","type":"village"},
            {"community_id":"5801262","name":"Վազգենաշեն","name_eng":"Vazgenashen","region_id":"58","type":"village"},
            {"community_id":"5801272","name":"Քարաբակ","name_eng":"Karabak","region_id":"58","type":"village"},
            {"community_id":"5801312","name":"Արծվաշեն","name_eng":"Artsvashen","region_id":"58","type":"village"},
            {"community_id":"5801322","name":"Մխանց","name_eng":"Mkhants","region_id":"58","type":"village"},
            {"community_id":"5801402","name":"Արտաշավի","name_eng":"Artashavi","region_id":"58","type":"village"},
            {"community_id":"5801512","name":"Գանձա","name_eng":"Gandza","region_id":"58","type":"village"},
            {"community_id":"5801522","name":"Բազմատուս","name_eng":"Bazmatus","region_id":"58","type":"village"},
            {"community_id":"5801602","name":"Գետամեջ","name_eng":"Getamej","region_id":"58","type":"village"},
            {"community_id":"5801702","name":"Գետափ","name_eng":"Getap","region_id":"58","type":"village"},
            {"community_id":"5801802","name":"Գողթանիկ","name_eng":"Goghtanik","region_id":"58","type":"village"},
            {"community_id":"5801912","name":"Դրախտաձոր","name_eng":"Drakhtadzor","region_id":"58","type":"village"},
            {"community_id":"5801922","name":"Անի","name_eng":"Ani","region_id":"58","type":"village"},
            {"community_id":"5802012","name":"Լեռնահովիտ","name_eng":"Lernahovit","region_id":"58","type":"village"},
            {"community_id":"5802022","name":"Շրվական","name_eng":"Shrvakan","region_id":"58","type":"village"},
            {"community_id":"5802032","name":"Սպիտակաջուր","name_eng":"Spitakajur","region_id":"58","type":"village"},
            {"community_id":"5802112","name":"Երիցվանք","name_eng":"Yeritsvank","region_id":"58","type":"village"},
            {"community_id":"5802122","name":"Ամիրյան","name_eng":"Amiryan","region_id":"58","type":"village"},
            {"community_id":"5802132","name":"Երվանդակերտ","name_eng":"Yervandakert","region_id":"58","type":"village"},
            {"community_id":"5802142","name":"Կրմեն","name_eng":"Krmen","region_id":"58","type":"village"},
            {"community_id":"5802202","name":"Իշխանաձոր","name_eng":"Ishkhanadzor","region_id":"58","type":"village"},
            {"community_id":"5802312","name":"Ծաղկաբերդ","name_eng":"Tsaghkaberd","region_id":"58","type":"village"},
            {"community_id":"5802322","name":"Մարաթուկ","name_eng":"Maratuk","region_id":"58","type":"village"},
            {"community_id":"5802412","name":"Ծիծեռնավանք","name_eng":"Tsitsernavank","region_id":"58","type":"village"},
            {"community_id":"5802422","name":"Արահուծ","name_eng":"Arahuts","region_id":"58","type":"village"},
            {"community_id":"5802432","name":"Մելիքաշեն","name_eng":"Melikashen","region_id":"58","type":"village"},
            {"community_id":"5802442","name":"Տանձուտ","name_eng":"Tandzut","region_id":"58","type":"village"},
            {"community_id":"5802512","name":"Ծոբաձոր","name_eng":"Tsobadzor","region_id":"58","type":"village"},
            {"community_id":"5802522","name":"Որդուակ","name_eng":"Vorduak","region_id":"58","type":"village"},
            {"community_id":"5802612","name":"Կերեն","name_eng":"Keren","region_id":"58","type":"village"},
            {"community_id":"5802622","name":"Գրհամ","name_eng":"Grham","region_id":"58","type":"village"},
            {"community_id":"5802632","name":"Սպիտակաշեն","name_eng":"Spitakashen","region_id":"58","type":"village"},
            {"community_id":"5802712","name":"Կումայրի","name_eng":"Kumayri","region_id":"58","type":"village"},
            {"community_id":"5802722","name":"Շիրակ","name_eng":"Shirak","region_id":"58","type":"village"},
            {"community_id":"5802802","name":"Հակ","name_eng":"Hak","region_id":"58","type":"village"},
            {"community_id":"5802902","name":"Հակարի","name_eng":"Hakari","region_id":"58","type":"village"},
            {"community_id":"5803012","name":"Հայկազյան","name_eng":"Haykazyan","region_id":"58","type":"village"},
            {"community_id":"5803022","name":"Դարբնոց","name_eng":"Darbnots","region_id":"58","type":"village"},
            {"community_id":"5803032","name":"Ջանֆիդա","name_eng":"Janfida","region_id":"58","type":"village"},
            {"community_id":"5803042","name":"Սահառ","name_eng":"Sahar","region_id":"58","type":"village"},
            {"community_id":"5803102","name":"Հոչանց","name_eng":"Hochants","region_id":"58","type":"village"},
            {"community_id":"5803202","name":"Ձորափ","name_eng":"Dzorap","region_id":"58","type":"village"},
            {"community_id":"5803302","name":"Ղազարապատ","name_eng":"Ghazarapat","region_id":"58","type":"village"},
            {"community_id":"5803412","name":"Մամարք","name_eng":"Mamark","region_id":"58","type":"village"},
            {"community_id":"5803422","name":"Հալե","name_eng":"Hale","region_id":"58","type":"village"},
            {"community_id":"5803502","name":"Մարտունաշեն","name_eng":"Martunashen","region_id":"58","type":"village"},
            {"community_id":"5803602","name":"Միրիկ","name_eng":"Mirik","region_id":"58","type":"village"},
            {"community_id":"5803712","name":"Մշենի","name_eng":"Msheni","region_id":"58","type":"village"},
            {"community_id":"5803722","name":"Արվական","name_eng":"Arvakan","region_id":"58","type":"village"},
            {"community_id":"5803812","name":"Մոշաթաղ","name_eng":"Moshatagh","region_id":"58","type":"village"},
            {"community_id":"5803822","name":"Հերիկ","name_eng":"Herik","region_id":"58","type":"village"},
            {"community_id":"5803832","name":"Բերդիկ","name_eng":"Berdik","region_id":"58","type":"village"},
            {"community_id":"5803902","name":"Մուշ","name_eng":"Mush","region_id":"58","type":"village"},
            {"community_id":"5804012","name":"Նորաշենիկ","name_eng":"Norashenik","region_id":"58","type":"village"},
            {"community_id":"5804022","name":"Վարդուտ","name_eng":"Vardut","region_id":"58","type":"village"},
            {"community_id":"5804112","name":"Շալուա","name_eng":"Shalua","region_id":"58","type":"village"},
            {"community_id":"5804122","name":"Հիմնաշեն","name_eng":"Himnashen","region_id":"58","type":"village"},
            {"community_id":"5804132","name":"Վերին շեն","name_eng":"Verin Shen","region_id":"58","type":"village"},
            {"community_id":"5804142","name":"Քարուտ","name_eng":"Karut","region_id":"58","type":"village"},
            {"community_id":"5804202","name":"Սարատակ","name_eng":"Saratak","region_id":"58","type":"village"},
            {"community_id":"5804312","name":"Սոնասար","name_eng":"Sonasar","region_id":"58","type":"village"},
            {"community_id":"5804322","name":"Մարգիս","name_eng":"Margis","region_id":"58","type":"village"},
            {"community_id":"5804412","name":"Ներքին Սուս","name_eng":"Nerkin Sus","region_id":"58","type":"village"},
            {"community_id":"5804422","name":"Գիհուտ","name_eng":"Gihut","region_id":"58","type":"village"},
            {"community_id":"5804432","name":"Սուս","name_eng":"Sus","region_id":"58","type":"village"},
            {"community_id":"5804442","name":"Ուրմիա","name_eng":"Urmia","region_id":"58","type":"village"},
            {"community_id":"5804512","name":"Վակունիս","name_eng":"Vakunis","region_id":"58","type":"village"},
            {"community_id":"5804522","name":"Խաչինտափ","name_eng":"Khachintap","region_id":"58","type":"village"},
            {"community_id":"5804532","name":"Չորմանք","name_eng":"Chormank","region_id":"58","type":"village"},
            {"community_id":"5804542","name":"Շամք","name_eng":"Shamk","region_id":"58","type":"village"},
            {"community_id":"5804612","name":"Վաղազին","name_eng":"Vaghazin","region_id":"58","type":"village"},
            {"community_id":"5804622","name":"Մարտիրոս","name_eng":"Martiros","region_id":"58","type":"village"},
            {"community_id":"5804702","name":"Վան","name_eng":"Van","region_id":"58","type":"village"},
            {"community_id":"5804812","name":"Վարդաբաց","name_eng":"Vardabats","region_id":"58","type":"village"},
            {"community_id":"5804822","name":"Քարոտան","name_eng":"Karotan","region_id":"58","type":"village"},
            {"community_id":"5804902","name":"Վուրգավան","name_eng":"Vurgavan","region_id":"58","type":"village"},
            {"community_id":"5805002","name":"Տիգրանավան","name_eng":"Tigranavan","region_id":"58","type":"village"},
            {"community_id":"5805102","name":"Ուռեկան","name_eng":"Urekan","region_id":"58","type":"village"},
            {"community_id":"5805202","name":"Փակահան","name_eng":"Pakahan","region_id":"58","type":"village"},
            {"community_id":"5805312","name":"Քաշունիք","name_eng":"Kashunik","region_id":"58","type":"village"},
            {"community_id":"5805322","name":"Մորաջուր","name_eng":"Morajur","region_id":"58","type":"village"},
            {"community_id":"5805332","name":"Վերին Քաշունիք","name_eng":"Verin Kashunik","region_id":"58","type":"village"},
            {"community_id":"5805402","name":"Քարեգահ","name_eng":"Karegah","region_id":"58","type":"village"}
        ]
      
          await knex('communities').insert(communities);
      }
    },
  
    async down(knex) {},
  };









